-- MySQL Script generated by MySQL Workbench
-- Tue Jan  6 15:01:06 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema centro_cocreacion
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema centro_cocreacion
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `centro_cocreacion` ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `id` INT NOT NULL,
  `usuarioscol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

USE `centro_cocreacion` ;

-- -----------------------------------------------------
-- Table `centro_cocreacion`.`Autenticación`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `centro_cocreacion`.`Autenticación` (
  `id auth` INT NULL,
  `email` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NULL,
  PRIMARY KEY (`id auth`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `centro_cocreacion`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `centro_cocreacion`.`roles` (
  `id_rol` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(150) NULL DEFAULT NULL,
  `Autenticación_id auth` INT NOT NULL,
  PRIMARY KEY (`id_rol`),
  INDEX `fk_roles_Autenticación1_idx` (`Autenticación_id auth` ASC) VISIBLE,
  CONSTRAINT `fk_roles_Autenticación1`
    FOREIGN KEY (`Autenticación_id auth`)
    REFERENCES `centro_cocreacion`.`Autenticación` (`id auth`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `centro_cocreacion`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `centro_cocreacion`.`usuarios` (
  `id_usuario` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `apellido` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `Autenticación_id auth` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX (`email` ASC) VISIBLE,
  INDEX `fk_usuarios_Autenticación1_idx` (`Autenticación_id auth` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_Autenticación1`
    FOREIGN KEY (`Autenticación_id auth`)
    REFERENCES `centro_cocreacion`.`Autenticación` (`id auth`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);



-- -----------------------------------------------------
-- Table `centro_cocreacion`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `centro_cocreacion`.`categoria` (
  `idcategoria` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `centro_cocreacion`.`emprendimientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `centro_cocreacion`.`emprendimientos` (
  `id_emprendimiento` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `id_emprendedor` INT NOT NULL,
  `categoria_idcategoria` INT NOT NULL,
  PRIMARY KEY (`id_emprendimiento`),
  INDEX (`id_emprendedor` ASC) VISIBLE,
  INDEX `fk_emprendimientos_categoria1_idx` (`categoria_idcategoria` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`id_emprendedor`)
    REFERENCES `centro_cocreacion`.`usuarios` (`id_usuario`),
  CONSTRAINT `fk_emprendimientos_categoria1`
    FOREIGN KEY (`categoria_idcategoria`)
    REFERENCES `centro_cocreacion`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `centro_cocreacion`.`mentorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `centro_cocreacion`.`mentorias` (
  `id_mentoria` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `tema` VARCHAR(100) NULL DEFAULT NULL,
  `id_tutor` INT NOT NULL,
  `id_emprendedor` INT NOT NULL,
  `id_emprendimiento` INT NOT NULL,
  PRIMARY KEY (`id_mentoria`),
  INDEX (`id_tutor` ASC) VISIBLE,
  INDEX (`id_emprendedor` ASC) VISIBLE,
  INDEX (`id_emprendimiento` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`id_tutor`)
    REFERENCES `centro_cocreacion`.`tutores` (`id_tutor`),
  CONSTRAINT ``
    FOREIGN KEY (`id_emprendedor`)
    REFERENCES `centro_cocreacion`.`usuarios` (`id_usuario`),
  CONSTRAINT ``
    FOREIGN KEY (`id_emprendimiento`)
    REFERENCES `centro_cocreacion`.`emprendimientos` (`id_emprendimiento`));


-- -----------------------------------------------------
-- Table `centro_cocreacion`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `centro_cocreacion`.`estado` (
  `idestado` INT NOT NULL,
  `creacion` VARCHAR(45) NULL,
  `revision` VARCHAR(45) NULL,
  `publicacion` VARCHAR(45) NULL,
  PRIMARY KEY (`idestado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `centro_cocreacion`.`progreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `centro_cocreacion`.`progreso` (
  `id_progreso` INT NULL AUTO_INCREMENT,
  `id_emprendimiento` INT NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  `estado_idestado` INT NOT NULL,
  PRIMARY KEY (`id_progreso`),
  INDEX (`id_emprendimiento` ASC) VISIBLE,
  INDEX `fk_progreso_estado1_idx` (`estado_idestado` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`id_emprendimiento`)
    REFERENCES `centro_cocreacion`.`emprendimientos` (`id_emprendimiento`),
  CONSTRAINT `fk_progreso_estado1`
    FOREIGN KEY (`estado_idestado`)
    REFERENCES `centro_cocreacion`.`estado` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `centro_cocreacion`.`especialidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `centro_cocreacion`.`especialidad` (
  `idespecialidad` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `servicios` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idespecialidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `centro_cocreacion`.`colaboradores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `centro_cocreacion`.`colaboradores` (
  `id_colaboradores` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `usuarios_id_usuario` INT NOT NULL,
  `especialidad_idespecialidad` INT NOT NULL,
  PRIMARY KEY (`id_colaboradores`),
  INDEX `fk_colaboradores_usuarios1_idx` (`usuarios_id_usuario` ASC) VISIBLE,
  INDEX `fk_colaboradores_especialidad1_idx` (`especialidad_idespecialidad` ASC) VISIBLE,
  CONSTRAINT `fk_colaboradores_usuarios1`
    FOREIGN KEY (`usuarios_id_usuario`)
    REFERENCES `centro_cocreacion`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_colaboradores_especialidad1`
    FOREIGN KEY (`especialidad_idespecialidad`)
    REFERENCES `centro_cocreacion`.`especialidad` (`idespecialidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `centro_cocreacion`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `centro_cocreacion`.`table1` (
)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
